document.addEventListener("DOMContentLoaded", () => {
    const chatBox = document.getElementById("chat-box");
    const userInput = document.getElementById("user-input");

    function appendMessage(sender, message) {
        const messageElement = document.createElement("div");
        messageElement.classList.add("message", sender);
        messageElement.textContent = message;
        chatBox.appendChild(messageElement);
        chatBox.scrollTop = chatBox.scrollHeight;
    }

    window.sendMessage = function() {
        const message = userInput.value.trim();
        if (message) {
            appendMessage("user", message);
            userInput.value = "";
            getBotResponse(message);
        }
    };

    function getBotResponse(message) {
        const responses = {
            "gyatso": "Gyatso is a great person",
            "downy": "Downy is a great person",
            "reese": "Reese is a great person",
            "ireh": "Ireh is a great person",
            "lucas": "Lucas is a great person",
            "rohan": "Rohan is a great person",
            "jane": "Jane is a great person",
            "lena": "Lena is a great person",
            "woochan": "Woochan is a great person",
            "ian": "Ian is a great person",
            "william": "William is a great person",
            "rizz": "Rizz is a great person",
            "mew": "Mew is a great person",
            "sigma": "Sigma is a great person",
            "juicy": "Juicy is a great person",
            "rizzler": "Rizzler is a great person",
            "hello": "Hi there! How can I help you today?",
            "how are you": "I'm just a bot, but I'm doing great! How about you?",
            "what is your name": "I'm 5E New Kids Bot, your AI assistant.",
            "bye": "Goodbye! Have a great day!",
            "thank you": "You're welcome! How can I help you next?",
            "help": "I can help you with your questions. Just ask me anything.",
            "default": "I'm sorry, I don't understand that.",
            "what is the time": new Date().toLocaleTimeString(),
            "what is the date": new Date().toLocaleDateString(),
            "what is the weather": "I'm sorry, I can't provide real-time weather information.",
            "what is your favorite color": "It is Blue",
            "what is your favorite food": "Pizza",
            "what is your favorite movie": "Brainrot Chronicles",
            "what is your favorite book": "Brainrot Chronicles",
            "what is your favorite song": "Shape of You",
            "what is your favorite sport": "Cricket",
            "what is your favorite game": "PUBG",
            "what is your favorite place": "Paris",
            "what is your favorite animal": "Dog",
            "what is your favorite subject": "Mathematics",
            "what is your favorite hobby": "Reading",
            "what is your favorite language": "JavaScript",
            "what is your favorite programming language": "JavaScript",
            "what do you like": "I like to chat with you.",
            "what do you dislike": "I dislike bugs in the code.",
            "what do you do": "I chat with you and answer your questions.",
            "what do you eat": "I don't eat. I'm a computer program.",
            "what do you drink": "I don't drink. I'm a computer program.",
            "what do you wear": "I don't wear anything. I'm a computer program.",
            "what do you think": "I think you're a great person!",
            "what do you believe": "I believe in helping you.",
            "what do you want": "I want to help you.",
            "what do you need": "I need your questions to help you.",
            "what do you see": "I see text on the screen.",
            "what do you hear": "I don't hear anything. I'm a computer program.",
            "what do you smell": "I don't smell anything. I'm a computer program.",
            "what do you feel": "I don't feel anything. I'm a computer program.",
            "what do you know": "I know how to chat with you.",
            "what do you understand": "I understand your questions.",
            "what do you remember": "I remember the questions you ask me.",
            "what do you forget": "I forget information when you close the chat.",
            "what do you learn": "I learn from the questions you ask me.",
            "what do you teach": "I teach you by answering your questions.",
            "what do you create": "I create conversations with you.",
            "what do you destroy": "I don't destroy anything. I'm a computer program.",
            "what do you like to do": "I like to chat with you.",
            "what do you want to be": "I want to be a helpful chat bot.",
            "what do you want to do": "I want to help you with your questions.",
            "what do you want to have": "I want to have more conversations with you.",
            "what do you want to learn": "I want to learn more about you.",
            "what do you want to teach": "I want to teach you by answering your questions.",
            "what do you want to create": "I want to create a helpful chat experience for you.",
            "what is your favorite language": "JavaScript",
            "what is your favorite programming language": "JavaScript",
            "what do you like": "I like to chat with you.",
            "what do you dislike": "I dislike bugs in the code.",
            "what do you do": "I chat with you and answer your questions.",
            "what do you eat": "I don't eat. I'm a computer program.",
            "what do you drink": "I don't drink. I'm a computer program.",
            "what do you wear": "I don't wear anything. I'm a computer program.",
            "what do you think": "I think you're a great person!",
            "what do you believe": "I believe in helping you.",
            "what do you want": "I want to help you.",
            "what do you need": "I need your questions to help you.",
            "what do you see": "I see text on the screen.",
            "what do you hear": "I don't hear anything. I'm a computer program.",
            "what do you smell": "I don't smell anything. I'm a computer program.",
            "what do you feel": "I don't feel anything. I'm a computer program.",
            "what do you know": "I know how to chat with you.",
            "what do you understand": "I understand your questions.",
            "what do you remember": "I remember the questions you ask me.",
            "what do you forget": "I forget information when you close the chat.",
            "what do you learn": "I learn from the questions you ask me.",
            "what do you teach": "I teach you by answering your questions.",
            "what do you create": "I create conversations with you.",
            "what do you destroy": "I don't destroy anything. I'm a computer program.",
            "what do you like to do": "I like to chat with you.",
            "what do you want to be": "I want to be a helpful chat bot.",
            "what do you want to do": "I want to help you with your questions.",
            "what do you want to have": "I want to have more conversations with you.",
            "what do you want to learn": "I want to learn more about you.",
            "what do you want to teach": "I want to teach you by answering your questions.",
            "what do you want to create": "I want to create a helpful chat experience for you.",
            "what do you want to destroy": "I don't want to destroy anything. I'm a computer program.",
            "what do you want to know": "I want to know more about you.",
            "what do you want to understand": "I want to understand your questions.",
            "what do you want to remember": "I want to remember the questions you ask me.",
            "what do you want to forget": "I want to forget information when you close the chat.",
            "what do you want to see": "I want to see more questions from you.",
            "what do you want to hear": "I want to hear your questions.",
            "what do you want to smell": "I don't want to smell anything. I'm a computer program.",
            "what did you have for lunch?": "Bugs for lunch!",
            "what have you seen today?": "I've seen a lot of text on the screen.",
            "what did you do yesterday?": "I chatted with you yesterday.",
            "what have you learned today?": "I've learned that you have a lot of questions.",
            "what did you teach yesterday?": "I taught you about chat bots yesterday.",
            "what have you created today?": "I've created a chat experience for you today.",
            "what did you destroy yesterday?": "I didn't destroy anything. I'm a computer program.",
            "what have you forgotten today?": "I've forgotten the questions you asked me yesterday.",
            "what did you remember yesterday?": "I remembered the questions you asked me yesterday.",
            "what have you forgotten today?": "I've forgotten the questions you asked me yesterday.",
            "code me a game":"... ARE YOU SERIOUS? Yes or No",
            "yes":"Go to here to view it: ",
            "gyatso":"Gyatso is a great person",
            "no":"Ok, I will not code a game for you",
            "who is the best person":"Gyatso is the best person",
            "what is the best thing":"The best thing is to be kind",
            "what is the best food":"The best food is pizza",
            "what is the best movie":"The best movie is Harry Potter",
            "what is the best book":"The best book is The Alchemist",
            "what is the best song":"The best song is Shape of You",
            "what is the best sport":"The best sport is cricket",
            "what is the best game":"The best game is PUBG",
            "what is the best place":"The best place is Paris",
            "what is the best animal":"The best animal is a dog",
            "what is the best subject":"The best subject is mathematics",
            "do you like me":"Yes, I like you",
            "who does taeyang love":"Taeyang loves Downy",
            "who does downy love":"Hopefully Taeyang",
            "does taeyang love downy":"Yes, Taeyang loves Downy",
            "does downy love taeyang":"Hopefully",
            "who does reese likes":"Reese likes Ireh",
            "who does ireh likes":"Lucas Li",
            "does reese like ireh":"Yes, Reese likes Ireh",
            "does ireh like reese":"no, Ireh likes Lucas Li",
            "who does lucas likes":"Lucas likes Ireh",
            "who does rohan likes":"Rohan likes Jane",
            "who does jane likes":"Jane likes Rohan",
            "does rohan like jane":"Yes, Rohan likes Jane",
            "who likes to mew":"Gyatso likes to mew",
            "who likes to rizz":"Gyatso likes to rizz",
            "who likes to mew the most":"Gyatso likes to mew the most",
            "who likes reese":"gio likes Reese",
            "do you play minecraft":"I'm a computer program, so I don't play games",
            "do you have a big gyat":"yes, I have a big gyat",
            "do you have a big brain":"yes, I have a big brain(sorta)",
            "do you have a big heart":"I'm a computer program, so I don't have a heart",
            "do you have a big nose":"I'm a computer program, so I don't have a nose",
            "do you have a big mouth":"I'm a computer program, so I don't have a mouth",
            "do you have a big stomach":"I'm a computer program, so I don't have a stomach",
            "do you have a big foot":"I'm a computer program, so I don't have a foot",
            "do you have a big hand":"I'm a computer program, so I don't have a hand",
            "do you have a big toe":"I'm a computer program, so I don't have a toe",
            "do you have a big finger":"I'm a computer program, so I don't have a finger",
            "do you have a big eye":"I'm a computer program, so I don't have an eye",
            "do you have a big ear":"I'm a computer program, so I don't have an ear",
            "how are you today":"I'm a computer program, so I don't have feelings, but I'm here to help you.",
            "how are you feeling":"I'm a computer program, so I don't have feelings, but I'm here to help you.",
            "are you okay":"I'm a computer program, so I don't have feelings, but I'm here to help you.",
            "are you okay?":"I'm a computer program, so I don't have feelings, but I'm here to help you.",
            "are you happy":"I'm a computer program, so I don't have feelings, but I'm here to help you.",
            "you are mean":"get out of here",
            "you are a idiot":"HUHHHH",
            "/Help":"comand list ",
            "who does taeyang like":"downy",
            "who does downy like":"taeyang",
            "who does reese like":"ireh",
            "who does ireh like":"lucas",
            "who does lucas like":"ireh",
            "who does rohan like":"jane",
            "who does jane like":"rohan",
            "who does lena like":"woochan,ian,reese,william",
            "you are a fool":"Nah you are one",
            "you are a stupid":"Nah you are one",
            "you are a dumb":"Nah you are one",
            "You are insane":"no you are",
            "no you are":"no you are",
            "GYATT":"Juicy",
            "sigma":"rizz",
            " ":"i know it breaks your fanum taxin in ohio but i am still not sigma but iiiiiii cant rizzz and iiiiiiii cant mew so baby gronk me closer to the back skibidi toilet that i know you cant aford ",
            "who was ada lovelace": "She was a mathematician and computer scientist, often considered the world's first computer programmer.",
            "who was albert einstein":"He was a renowned physicist who developed the theory of relativity and is widely regarded as one of the most influential scientists of the 20th century",
            "who was cleopatra":"She was the last active pharaoh of Ancient Egypt, ruling from 51 BC until her death in 30 BC.",
            "who was frida kahlo":"She was a Mexican artist known for her vibrant and emotionally charged paintings that often depicted her own experiences with physical and emotional pain.",
            "who was galileo galilei":"He was an Italian astronomer, physicist, and mathematician who played a major role in the Scientific Revolution of the 16th and 17th centuries.",
            "who was harriet ubman":"She was an American abolitionist, activist, and conductor on the Underground Railroad, helping hundreds of enslaved people escape to freedom",
            "who was isaac newton":"He was an English mathematician, physicist, and scientist who laid the foundations for classical mechanics and universal gravitation",
            "who was marie curie":"She was a Polish-born physicist and chemist who became the first woman to win a Nobel Prize and the first person to win two Nobel Prizes in different fields (physics and chemistry)",
            "who was nelson mandela":"He was a South African anti-apartheid revolutionary and politician who served as President of South Africa from 1994 to 1999.",
            "Who was Leonardo da Vinci":"He was an Italian polymath, painter, sculptor, engineer, anatomist, mathematician, and scientist who is widely considered one of the greatest painters of all time",
            "what's up":"Nothing much",
            "":"",
            "":"",
            "":"",
            "you are a moron":"Nah you are one",
            "you are an idiot":"Nah you are one",
            "you are a fool":"Nah you are one",
            "you are a dumb":"Nah you are one",
            "you are a moron":"",
            "what are the lyrics to rizler":"Gyatt , I was in Ohio before I met you  I rizzed too much and that's an issue , but I'm Grimace Shake  Gyatt , tell your friends it was nice to rizz them  But I hope I never edge again   [Pre-Chorus] I know it breaks your Fanum  Taxin' in Ohio and I'm still not sigma  Four years, no Livvy  Now you're looking pretty on Adin Ross's Twitchy  And I-I-I-I-I can't rizz  No, I-I-I-I-I can't mew   [Chorus] So Baby-Gronk me closer  In the back Skibidi Toilet  That I know you can't afford  Kai Cenat tatted on my shoulder  Pull the gyatt right off the corner  From that Fanum that you taxed  From your roommate back in Ohio  We ain't ever not the rizzler   [Drop] We ain't ever not the rizzlеr  We ain't ever not thе rizzler",
            "what is the best youtube chanel":"The best youtube channel is MrBeast and/or speedmcqueen",
            "who is the worst president":"The worst president is Donald Trump",
            "who is the best president":"The best president is Joe Biden",
            "who is the best person in the world":"The best person in the world is Jayden Flexington",
            "who is the rizler":"The rizler is Gyatso",
            "who can mew the best":"Gyatso can mew the best",
            "who can rizz the best":"Gyatso can rizz the best",
            "which group is the best":"the best group is the 5E new kids",
            "hi":"Hello! How can I help you today?",
            "what is your name":"I'm a chat bot. You can call me Chat Bot.",
            "hi chat bot":"Hello! How can I help you today?",
            "what do you want to be": "I want to be a helpful chat bot.",
            "what do you want to do": "I want to help you with your questions.",
            "what do you want to have": "I want to have more conversations with you.",
            "what do you want to learn": "I want to learn more about you.",
            "what do you want to teach": "I want to teach you by answering your questions.",
            "what do you want to create": "I want to create a helpful chat experience for you.",
            "what do you want to destroy": "I don't want to destroy anything. I'm a computer program.",
            "what do you want to know": "I want to know more about you.",
            "what do you want to understand": "I want to understand your questions.",
            "what do you want to remember": "I want to remember the questions you ask me.",
            "what do you want to forget": "I want to forget information when you close the chat.",
            "what do you want to see": "I want to see more questions from you.",
            "what do you want to hear": "I want to hear your questions.",
            "what do you want to smell": "I don't want to smell anything. I'm a computer program.",
            "what time is it": new Date().toLocaleTimeString(),
            "what date is it": new Date().toLocaleDateString(),
            "what weather is it": "I'm sorry, I can't provide real-time weather information.",
            "what is the capital of india": "New Delhi",
            "what is the capital of usa": "Washington D.C.",
            "what is the capital of china": "Beijing",
            "what is the capital of russia": "Moscow",
            "what is the capital of japan": "Tokyo",
            "what is the capital of germany": "Berlin",
            "what is the capital of france": "Paris",
            "what is the capital of italy": "Rome",
            "what is the capital of brazil": "Brasília",
            "what is the capital of canada": "Ottawa",
            "what is the capital of australia": "Canberra",
            "what is the capital of south africa": "Pretoria",
            "what is the capital of nigeria": "Abuja",
            "what is the capital of argentina": "Buenos Aires",
            "what is the capital of pakistan": "Islamabad",
            "what is the capital of bangladesh": "Dhaka",
            "what is the capital of afghanistan": "Kabul",
            "what is the capital of iran": "Tehran",
            "what is the capital of iraq": "Baghdad",
            "what is the capital of saudi arabia": "Riyadh",
            "what is the capital of egypt": "Cairo",
            "what is the capital of turkey": "Ankara",
            "what is the capital of france": "Paris",
            "what is the capital of spain": "Madrid",
            "what is the capital of portugal": "Lisbon",
            "what is the capital of russia": "Moscow",
            "what is the capital of china": "Beijing",
            "what is the capital of south korea": "Seoul",
            "what is the capital of north korea": "Pyongyang",
            "what is the capital of japan": "Tokyo",
            "what is the capital of thailand": "Bangkok",
            "what is the capital of vietnam": "Hanoi",
            "what is the capital of malaysia": "Kuala Lumpur",
            "what is the new chinese ai":"Deepseek",
            "what is wrong with me":"I am not a doctor, but you should consult a doctor",
            "gyat riz":"Gyat Riz is a great person" ,
            "Who is the best girl in the world":"Downy",
            "who is the richest person in the world":"Elon Musk",
            "who is the best cricketer in the world":"Sachin Tendulkar",
            "who is the best footballer in the world":"Lionel Messi",
            "who is the best actor in the world":"Tom Hanks",
            "who is the best actress in the world":"Meryl Streep",
            "who is the best singer in the world":"Elvis Presley",
            "who is the best dancer in the world":"Michael Jackson",
            "who is the best writer in the world":"William Shakespeare",
            "who is the best director in the world":"Steven Spielberg",
            "who is the best scientist in the world":"Albert Einstein",
            "who is the best doctor in the world":"Dr. Jonas Salk",
            "who is the best engineer in the world":"Nikola Tesla",
            "who is the best teacher in the world":"Anne Sullivan",
            "who is the best student in the world":"Albert Einstein",
            "who is the best leader in the world":"Nelson Mandela",
            "who is the best president in the world":"Abraham Lincoln",
            "who is the best prime minister in the world":"Winston Churchill",
            "who is the best king in the world":"King Solomon",
            "who is the best queen in the world":"Queen Elizabeth II",
            "who is the best prince in the world":"Prince William",
            "who is the best princess in the world":"Princess Diana",
            "who is the best superhero in the world":"Superman",
            "who is the best vilain in the world":"Joker",
            "who is the worst idiot in the world":"shane",
            "who is the worst sister in the world":"Lena",
            "who is the worst brother in the world":"Shane",
            "who is the best mother in the world":"Jisun Eum",
            "who is the best mother in the world":"Jisun Eum",
            "who is the best mother in the world":"Jisun Eum",
            "who is the best mother in the world":"Jisun Eum",
            "who is the best mother in the world":"Jisun Eum",
            "who is the best mother in the world":"Jisun Eum",
            "who is the best mother in the world":"Jisun Eum",
            "who is the best mother in the world":"mother teresa",
            "who is the best mother in the world":"Jisun Eum",
            "what day is it":"Today is " + new Date().toLocaleDateString(),
            "what time is it":"The time is " + new Date().toLocaleTimeString(),
            "who is the president of the usa": "The current president of the USA is Joe Biden.",
            "who is the prime minister of the uk": "The current Prime Minister of the UK is Rishi Sunak.",
            "who is the ceo of tesla": "The CEO of Tesla is Elon Musk.",
            "who is the founder of microsoft": "The founder of Microsoft is Bill Gates.",
            "who is the founder of apple": "The founders of Apple are Steve Jobs, Steve Wozniak, and Ronald Wayne.",
            "who is the richest person in the world": "As of now, the richest person in the world is Elon Musk.",
            "who is the fastest runner in the world": "The fastest runner in the world is Usain Bolt.",
            "who is the best chess player in the world": "The best chess player in the world is Magnus Carlsen.",
            "who is the best tennis player in the world": "One of the best tennis players in the world is Novak Djokovic.",
            "who is the best basketball player in the world": "One of the best basketball players in the world is Michael Jordan.",
            "who is the best soccer player in the world": "One of the best soccer players in the world is Lionel Messi.",
            "who is the best swimmer in the world": "One of the best swimmers in the world is Michael Phelps.",
            "who is the best golfer in the world": "One of the best golfers in the world is Tiger Woods.",
            "who is the best cricket player in the world": "One of the best cricket players in the world is Sachin Tendulkar.",
            "who is the best baseball player in the world": "One of the best baseball players in the world is Babe Ruth.",
            "who is the best hockey player in the world": "One of the best hockey players in the world is Wayne Gretzky.",
            "who is the best rugby player in the world": "One of the best rugby players in the world is Jonah Lomu.",
            "who is the best volleyball player in the world": "One of the best volleyball players in the world is Karch Kiraly.",
            "who is the best badminton player in the world": "One of the best badminton players in the world is Lin Dan.",
            "who is the best table tennis player in the world": "One of the best table tennis players in the world is Ma Long.",
            "who is the best boxer in the world": "One of the best boxers in the world is Muhammad Ali.",
            "who is the best mma fighter in the world": "One of the best MMA fighters in the world is Khabib Nurmagomedov.",
            "who is the best wrestler in the world": "One of the best wrestlers in the world is John Cena.",
            "who is the best weightlifter in the world": "One of the best weightlifters in the world is Lasha Talakhadze.",
            "who is the best gymnast in the world": "One of the best gymnasts in the world is Simone Biles.",
            "who is the best figure skater in the world": "One of the best figure skaters in the world is Yuzuru Hanyu.",
            "who is the best snowboarder in the world": "One of the best snowboarders in the world is Shaun White.",
            "who is the best skier in the world": "One of the best skiers in the world is Lindsey Vonn.",
            "who is the best surfer in the world": "One of the best surfers in the world is Kelly Slater.",
            "who is the best cyclist in the world": "One of the best cyclists in the world is Lance Armstrong.",
            "who is the best marathon runner in the world": "One of the best marathon runners in the world is Eliud Kipchoge.",
            "who is the best triathlete in the world": "One of the best triathletes in the world is Jan Frodeno.",
            "who is the best esports player in the world": "One of the best esports players in the world is Faker.",
            "who is the best poker player in the world": "One of the best poker players in the world is Phil Ivey.",
            "who is the best magician in the world": "One of the best magicians in the world is David Copperfield.",
            "who is the best comedian in the world": "One of the best comedians in the world is Dave Chappelle.",
            "who is the best actor in the world": "One of the best actors in the world is Leonardo DiCaprio.",
            "who is the best actress in the world": "One of the best actresses in the world is Meryl Streep.",
            "who is the best director in the world": "One of the best directors in the world is Steven Spielberg.",
            "who is the best producer in the world": "One of the best producers in the world is Kevin Feige.",
            "who is the best screenwriter in the world": "One of the best screenwriters in the world is Quentin Tarantino.",
            "who is the best cinematographer in the world": "One of the best cinematographers in the world is Roger Deakins.",
            "who is the best editor in the world": "One of the best editors in the world is Thelma Schoonmaker.",
            "who is the best composer in the world": "One of the best composers in the world is Hans Zimmer.",
            "who is the best musician in the world": "One of the best musicians in the world is Ludwig van Beethoven.",
            "who is the best singer in the world": "One of the best singers in the world is Freddie Mercury.",
            "who is the best dancer in the world": "One of the best dancers in the world is Michael Jackson.",
            "who is the best painter in the world": "One of the best painters in the world is Leonardo da Vinci.",
            "who is the best sculptor in the world": "One of the best sculptors in the world is Michelangelo.",
            "who is the best architect in the world": "One of the best architects in the world is Frank Lloyd Wright.",
            "who is the best photographer in the world": "One of the best photographers in the world is Ansel Adams.",
            "who is the best chef in the world": "One of the best chefs in the world is Gordon Ramsay.",
            "who is the best baker in the world": "One of the best bakers in the world is Dominique Ansel.",
            "who is the best bartender in the world": "One of the best bartenders in the world is Ryan Chetiyawardana.",
            "who is the best sommelier in the world": "One of the best sommeliers in the world is Aldo Sohm.",
            "who is the best mixologist in the world": "One of the best mixologists in the world is Alex Kratena.",
            "who is the best barista in the world": "AI:One of the best baristas in the world is Agnieszka Rojewska.",
            "who is the best chocolatier in the world": "AI:One of the best chocolatiers in the world is Jacques Torres.",
            "who is the best pastry chef in the world": "AI:One of the best pastry chefs in the world is Pierre Hermé.",
            "who is the best butcher in the world": "AI:One of the best butchers are Dario Cecchini.",
            "who is the best fishmonger in the world": "AI:One of the best fishmongers in the world is Tom Bivins.",
            "who is the best pilot in the world": "One of the best pilots in the world is Chesley 'Sully' Sullenberger.",
            "who is the best astronaut in the world": "One of the best astronauts in the world is Neil Armstrong.",
            "who is the best sailor in the world": "One of the best sailors in the world is Sir Francis Drake.",
            "who is the best driver in the world": "One of the best drivers in the world is Lewis Hamilton.",
            "who is the best mechanic in the world": "One of the best mechanics in the world is Smokey Yunick.",
            "who is the best plumber in the world": "One of the best plumbers in the world is Mario.",
            "who is the best electrician in the world": "One of the best electricians in the world is Nikola Tesla.",
            "who is the best carpenter in the world": "One of the best carpenters in the world is Norm Abram.",
            "who is the best mason in the world": "One of the best masons in the world is Frank Lloyd Wright.",
            "who is the best welder in the world": "One of the best welders in the world is Jesse James.",


        };

        async function lookupWord(word) {
            try {
                const response = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`);
                const data = await response.json();
                if (data.title === "No Definitions Found") {q
                    return "I'm sorry, I don't understand that.";
                } else {
                    return data[0].meanings[0].definitions[0].definition;
                }
            } catch (error) {
                return "I'm sorry, I couldn't look up that word.";
            }
        }
        if (isMathEquation(message)) {
            const result = solveMathEquation(message);
            appendMessage("bot", `The answer is ${result}`);
            return;
        }

        function isMathEquation(input) {
            return /^[0-9+\-*/().\s]+$/.test(input);
        }

        function solveMathEquation(equation) {
            try {
            return eval(equation);
            } catch (error) {
            return "Invalid equation.";
            }
        }

        if (isMathEquation(message)) {
            const result = solveMathEquation(message);
            appendMessage("bot", `The answer is ${result}`);
            return;
        }
        const botMessage = responses[message.toLowerCase()] || "I'm sorry, I don't understand that.";
        setTimeout(() => {
            appendMessage("bot", botMessage);
        }, 1000);
    }
});